site_name: "ITMO ICT WebDevelopment 2025-2026"
site_description: "Отчеты по лабораторным работам курса Web Development"
site_author: "Якшин Артемий"
site_url: "https://cicada-pops.github.io/TonikX-ITMO_ICT_WebDevelopment_2025-2026/"

docs_dir: docs

nav:
  - Главная: index.md
  - Лабораторная работа 1: lab1.md
  - Лабораторная работа 2: lab2.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - toc:
      permalink: true
      title: On this page
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search:
      lang: ru
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cicada-pops
  version:
    provider: mike
